[package]
name = "telemetroid"
version = "0.1.0"
edition = "2024"

[dependencies]
teloxide = { version = "0.17.0", default-features = false, features = ["macros", "ctrlc_handler", "rustls"] }
log = "0.4.30"
thiserror = "2.0.18"
pretty_env_logger = "0.5"
tokio = { version =  "1.52.3", features = ["rt-multi-thread", "macros", "signal"] }
serde_json = { version = "1.0.150" }
serde = { version = "1.0.228", features = ["derive"] }
